version: '3.7'

services:

  evolution-api:
    container_name: evolution_api-prod
    image: atendai/evolution-api:v1.8.0
    restart: always
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_URL=${SERVER_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_METHODS=${CORS_METHODS}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS}
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME}
      - QRCODE_LIMIT=${QRCODE_LIMIT}
      - AUTHENTICATION_TYPE=${AUTHENTICATION_TYPE}
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
    ports:
      - "8081:8080"
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - coolify

  next-app:
    container_name: next-app-prod
    build:
      context: ./
      dockerfile: ./app/prod.Dockerfile
      args:
        - NODE_ENV=production
        - ASAAS_LINK_PAGAMENTO_UNICO=${ASAAS_LINK_PAGAMENTO_UNICO}
        - ASAAS_LINK_PAGAMENTO_RECORRENTE=${ASAAS_LINK_PAGAMENTO_RECORRENTE}
        - EVOLUTION_API_URL=${EVOLUTION_API_URL}
        - DATABASE_URL=${DATABASE_URL}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - AUTH_URL=${AUTH_URL}
        - AUTH_REDIRECT_PROXY_URL=${AUTH_REDIRECT_PROXY_URL}
        - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
    restart: always
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
      - prisma_volume:/app/node_modules/@prisma
    ports:
      - 3000:3000
    depends_on:
      - evolution-api
    networks:
      - coolify

volumes:
  nextjs_cache:
  evolution_store:
  evolution_instances:
  prisma_volume: