version: '3.7'

services:
  next-app:
    container_name: test-app
    build:
      context: .
      dockerfile: ./app/dev.Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000

  # Add more containers below (nginx, postgres, etc.)

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true

volumes:
  nextjs_cache:
  postgres: